[profile.default]
src = "src"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
evm_version = 'paris'
optimizer = true
optimizer_runs = 200
ffi = true
ast = true
[rpc_endpoints]
mintTest = "https://sepolia-testnet-rpc.mintchain.io"
mint = "https://rpc.mintchain.io"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
